version: '2.1'
services:
  liferay:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./bundles/osgi/modules:/home/liferay/bundles/osgi/modules
      - ./bundles/deploy:/home/liferay/bundles/deploy
